version: "3.9"

services:
  client:
    build: .
    volumes:
      - "./client:/app"
    ports:
      - "3000:3000"
    depends_on:
      - api

  api:
    build: .
    volumes:
      - "./api:/app"
    ports:
      - "8000:8000"
    env_file:
      - api/.env
